services:
  mongodb:
    image: mongo:6
    container_name: safelive-mongo
    restart: always

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    container_name: safelive-backend
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - PRIORITY_AI_EXTERNAL_DATASET=/app/synthetic_complaints_datechange.csv,/app/civic_issues_with_severity-1.csv
    depends_on:
      - mongodb
    restart: always

  frontend:
    build: ./Frontend
    container_name: safelive-frontend
    ports:
      - "8080:80"
    env_file:
      - ./Frontend/.env
    restart: always
